### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bastien8060** [bastien8060/ESPChess#1]
- [ ] Onboard Chess engine / Minimax
- [ ] Create Game with Duration
- [ ] Analysis Board
- [ ] Puzzle + Computer Screen
- [ ] Wifi Ssid Picker
- [ ] GUI Connect to Chess.com
- [ ] Save session_key to spiff
- [ ] Automatic Spiff repair
- [ ] Skip wifi connect
- [ ] First Run Greeting
- [ ] NTP + timezone
- [ ] Battery Level + auto saving
- [ ] Symbol Keyboard
- [ ] | Confirm Move before play + cancel | Switch to | Resign + draw |
- [ ] Clocks
- [ ] Logout 
- [ ] Settings page for : 
    - [ ] debounce
    - [ ] confirm moves
    - [ ] OTA password
    - [ ] Power Settings
    - [ ] Brightness
    - [ ] Mdns
